# EdgeCloudX — Alert Service
---
apiVersion: v1
kind: Service
metadata:
  name: alert-service
  namespace: edgecloudx
  labels:
    app.kubernetes.io/name: alert-service
    app.kubernetes.io/part-of: edgecloudx
    app.kubernetes.io/component: api
spec:
  ports:
    - port: 8000
      targetPort: 8000
  selector:
    app.kubernetes.io/name: alert-service
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: alert-service
  namespace: edgecloudx
  labels:
    app.kubernetes.io/name: alert-service
    app.kubernetes.io/part-of: edgecloudx
    app.kubernetes.io/component: api
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: alert-service
  template:
    metadata:
      labels:
        app.kubernetes.io/name: alert-service
        app.kubernetes.io/part-of: edgecloudx
        app.kubernetes.io/component: api
    spec:
      containers:
        - name: alert-service
          image: edgex-alert-service:latest
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8000
          envFrom:
            - configMapRef:
                name: edgecloudx-config
          env:
            - name: SERVICE_NAME
              value: "alert-service"
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: edgecloudx-secrets
                  key: POSTGRES_PASSWORD
            - name: JWT_SECRET_KEY
              valueFrom:
                secretKeyRef:
                  name: edgecloudx-secrets
                  key: JWT_SECRET_KEY
          readinessProbe:
            httpGet:
              path: /health
              port: 8000
            initialDelaySeconds: 10
            periodSeconds: 10
          livenessProbe:
            httpGet:
              path: /health
              port: 8000
            initialDelaySeconds: 15
            periodSeconds: 20
          resources:
            requests:
              cpu: 50m
              memory: 96Mi
            limits:
              cpu: 300m
              memory: 256Mi
